on: [pull_request]
name: Frontend Build Check
jobs:
  frontend_build_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
      - name: Generate Rust Undeads Json
        run: cargo run && cp ./undeads.json ../frontend/undeads_rust.json
        working-directory: ./runtime-rs
      - name: Execute C++ Runtime
        uses: ./runtime_cc.yml
      - name: Copy C++ Undeads Json
        run: cp ./undeads.json ../frontend/undeads_cpp.json
        working-directory: ./runtime-cc
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: bahmutov/npm-install@v1
        with:
          useLockFile: true
          working-directory: ./frontend
      - name: Build Check
        run: yarn build
        working-directory: ./frontend
