on: [pull_request]
name: Rust Test
jobs:
  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
      - name: Test in Rust LeetCode
        run: cargo test
        working-directory: ./leetcode-rs
          
      - name: Test in Rust Runtime
        run: cargo test
        working-directory: ./runtime-rs
