on: [push, pull_request]
name: Rust Format Check
jobs:
  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
      - name: Setup Rustfmt
        run: rustup component add rustfmt
      - name: Format Check in LeetCode
        run: cargo fmt --all -- --check
        working-directory: ./leetcode
          
      - name: Format Check in Runtime
        run: cargo fmt --all -- --check
        working-directory: ./runtime
          
