on: [pull_request]
name: Rust Format Check
jobs:
  fmt_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
      - name: Setup Rustfmt
        run: rustup component add rustfmt
      - name: Format Check in Rust LeetCode
        run: cargo fmt --all -- --check
        working-directory: ./leetcode-rs
          
      - name: Format Check in Rust Runtime
        run: cargo fmt --all -- --check
        working-directory: ./runtime-rs
