on: [pull_request]
name: Rust Clippy Check
jobs:
  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
      - name: Setup Clippy
        run: rustup component add clippy
      - name: Clippy Check in LeetCode
        run: cargo clippy --all-targets --all-features -- -D warnings
        working-directory: ./leetcode
          
      - name: Clippy Check in Runtime
        run: cargo clippy --all-targets --all-features -- -D warnings
        working-directory: ./runtime
          

