on: [push, pull_request]
name: Rust Clippy Check
jobs:
  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
      - name: Clippy Check in LeetCode
        run: |
          cd ./leetcode
          cargo clippy --all-targets --all-features -- -D warnings
      - name: Clippy Check in Runtime
        run: |
          cd ./runtime
          cargo clippy --all-targets --all-features -- -D warnings

