on: [push, pull_request]
name: Rust Clippy Check
jobs:
  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            components: clippy
            override: true
      # switch to original when merged https://github.com/actions-rs/clippy-check/pull/158
      - uses: reinismu/clippy-check@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          working-directory: ./leetcode
      # switch to original when merged https://github.com/actions-rs/clippy-check/pull/158
      - uses: reinismu/clippy-check@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          working-directory: ./runtime
